namespace UnityEditor.PixyzPlugin4Unity.Toolbox
{
	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -20)]
		public static void A443952fa_34cf_4560_bcb1_43261f32ece6() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -19)]
		public static void A32883a0f_e679_45fd_8a3b_411c971561fc() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -18)]
		public static void Ad1618fca_5f07_41f6_ae8f_f9c65a99b1ad() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -17)]
		public static void A5e5ea72d_b582_4b52_a748_bccf8c23ced9() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -15)]
		public static void A53c29cf5_4166_4dbd_b2f4_e2762a89d21a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -14)]
		public static void Aafd49dfc_38a6_44fe_8302_6f12be02ccf9() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -13)]
		public static void Aabf5973d_7781_49be_ae93_38f1573d69ef() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -12)]
		public static void A6e540557_f176_46e3_a075_496e605a28ce() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -12)]
		public static void Aa5499f33_ae4d_4eea_8535_8a5802522292() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -11)]
		public static void A8f610106_fbbb_4174_ac55_2ec1502660c6() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -10)]
		public static void Af2e4a4bc_693a_4b62_973f_f46558419334() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -9)]
		public static void Ae2a47b10_968e_416b_b32e_9c887f8d5b4a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -8)]
		public static void A52b48c88_9992_4f23_9b0b_ba08b0cf7a8a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -7)]
		public static void A70d6f6a5_e01f_486b_9392_013d79d08f4f() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -6)]
		public static void Ac7564517_ebad_4da2_8ab5_3b826765bc4d() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -5)]
		public static void Adb5fd757_dbfe_4227_b68c_4c3daffb4b93() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -4)]
		public static void A3ca0b80e_e46e_4b99_adba_9911d9347fba() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -3)]
		public static void Aeb50cb1c_38f9_413b_b9af_e4fe2f4929f8() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateLightmapUVs()); }

	}
}